interface SmokeTestOptions {
  baseUrl: string;
  cleanup: boolean;
}

interface MetaResponse {
  configured?: boolean;
  repoUrl?: string | null;
  authMode?: string;
}

interface HealthResponse {
  ok?: boolean;
  repoConfigured?: boolean;
  submissionConfigured?: boolean;
  apiAuthConfigured?: boolean;
  authMode?: string;
}

interface CreateResponse {
  mode?: string;
  number?: number;
  url?: string;
  error?: string;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const baseUrl = options.baseUrl.replace(/\/$/, "");

  console.log(`Running Pages smoke test against ${baseUrl}`);

  const health = await getJson<HealthResponse>(`${baseUrl}/api/health`);
  assert(health.ok === true, "Health endpoint did not return ok: true.");
  assert(health.repoConfigured === true, "Health endpoint reported repoConfigured !== true.");
  assert(
    health.submissionConfigured === true,
    "Health endpoint reported submissionConfigured !== true."
  );
  assert(health.apiAuthConfigured === true, "Health endpoint reported apiAuthConfigured !== true.");
  assert(health.authMode === "app", `Expected authMode \"app\", received ${String(health.authMode)}.`);

  const meta = await getJson<MetaResponse>(`${baseUrl}/api/meta`);
  assert(meta.configured === true, "Meta endpoint reported configured !== true.");
  assert(Boolean(meta.repoUrl), "Meta endpoint did not expose a repoUrl.");

  const payload = buildSmokeRequest();
  const created = await postJson<CreateResponse>(`${baseUrl}/api/requests`, payload);

  assert(created.mode === "created", `Expected issue creation mode \"created\", received ${String(created.mode)}.`);
  assert(typeof created.number === "number", "Create response did not include an issue number.");
  assert(Boolean(created.url), "Create response did not include an issue URL.");

  console.log(`Created smoke test issue #${created.number}: ${created.url}`);

  if (options.cleanup) {
    const repo = parseRepoFromUrl(meta.repoUrl!);
    await closeIssue(repo.owner, repo.repo, created.number!);
    console.log(`Closed smoke test issue #${created.number}`);
  }
}

function parseArgs(argv: string[]): SmokeTestOptions {
  let baseUrl = "https://openreactor.net";
  let cleanup = false;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];

    if (arg === "--base-url") {
      const value = argv[index + 1];
      assert(Boolean(value), "Missing value for --base-url.");
      baseUrl = value!;
      index += 1;
      continue;
    }

    if (arg === "--cleanup") {
      cleanup = true;
      continue;
    }

    if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return { baseUrl, cleanup };
}

function printHelp(): void {
  console.log(`Usage: bun run smoke:pages -- [--base-url <url>] [--cleanup]

Options:
  --base-url <url>  Base URL to verify. Defaults to https://openreactor.net
  --cleanup         Close the created GitHub issue after a successful smoke test
`);
}

async function getJson<T>(url: string): Promise<T> {
  const response = await fetch(url, {
    headers: {
      Accept: "application/json"
    }
  });

  if (!response.ok) {
    throw new Error(`GET ${url} failed with ${response.status}.`);
  }

  return (await response.json()) as T;
}

async function postJson<T>(url: string, body: unknown): Promise<T> {
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    throw new Error(`POST ${url} failed with ${response.status}: ${await response.text()}`);
  }

  return (await response.json()) as T;
}

function buildSmokeRequest(): Record<string, string> {
  const timestamp = new Date().toISOString();

  return {
    name: "OpenReactor Smoke Test",
    contact: "@rayzhudev",
    summary: `Pages smoke test ${timestamp}`,
    problem: `Verify that the live Pages deployment can create a real GitHub issue through the configured GitHub App at ${timestamp}.`,
    outcome: "The API creates a real issue and returns mode created with the issue number and URL.",
    constraints: "Production verification only. Safe to close immediately after creation.",
    successCriteria: "The response includes mode created, an issue number, and a GitHub issue URL.",
    notes: "Generated by the repo smoke test command."
  };
}

function parseRepoFromUrl(repoUrl: string): { owner: string; repo: string } {
  const url = new URL(repoUrl);
  const [owner, repo] = url.pathname.replace(/^\/+/, "").split("/");

  assert(Boolean(owner && repo), `Unable to parse owner/repo from ${repoUrl}.`);
  return { owner: owner!, repo: repo! };
}

async function closeIssue(owner: string, repo: string, issueNumber: number): Promise<void> {
  const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN;
  assert(Boolean(token), "Cleanup requested but GH_TOKEN or GITHUB_TOKEN is not set.");

  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues/${issueNumber}`, {
    method: "PATCH",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "User-Agent": "OpenReactor Pages Smoke Test",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      state: "closed",
      state_reason: "not_planned"
    })
  });

  if (!response.ok) {
    throw new Error(`Failed to close smoke test issue #${issueNumber}: ${response.status} ${await response.text()}`);
  }
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) {
    throw new Error(message);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
